[package]
name = "cpucat"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1.3"
nix = "0.26.1"
num_cpus = "1.15.0"
