name: cpucat
base: core20 # the base snap is the execution environment for this snap
version: '0.1.8'
summary: Color your program output according to cpu usage # 79 char long summary
description: |
  This program reads the standard input and pipes it to the standard output
  using colors to indicate cpu usage at the time of printing a line from red
  being 100% usage and green being 0%.
icon: docs/cat.svg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  cpucat-part:
    # See 'snapcraft plugins'
    plugin: rust
    source: .

apps:
  cpucat-app:
    command: bin/cpucat
